// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentRemover
{
    static class Vsix
    {
        public const string Id = "d7c3f904-cc5a-4d47-aa25-81fb7c36df89";
        public const string Name = "Comment Remover";
        public const string Description = "Remove all comments in any file with a click of a button. Can also remove #regions and preserve XML Doc comments.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "comment, cleanup, delete, region, XMLDoc";
    }
}
